# Generated by Django 2.1.5 on 2019-02-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('canal', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
            ],
        ),
    ]
