# Generated by Django 2.1.5 on 2019-02-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='obs',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
